version: '3'

services:
  nginx:
    build: .
    ports:
      - "3000:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./build:/usr/share/nginx/html
    restart: unless-stopped
    network_mode: "host"
